### ISSUE TITLE
Trying to sign fit container without any luck.

### ISSUE THREAD

**Issue by dev-0x7C6** [rkraevskiy/ubootpubkey#2]
Hi,

I'm trying sign FIT container without any luck for sometime. This is my current workspace with [setup.sh](https://github.com/dev-0x7C6/fit-signing-tests/blob/main/setup.sh) which contains steps and comments what I'm doing.

I would be grateful for your help. This is my workspace:
https://github.com/dev-0x7C6/fit-signing-tests

Regards,
Bartłomiej

**Comment by rkraevskiy** [comment]
What problem do you have? What step has failed from setup.sh?

**Comment by dev-0x7C6** [comment]
I think I managed to fix it.

Firstly by correcting: https://github.com/dev-0x7C6/fit-signing-tests/commit/41cf42e42d58cb7d9c131db94d9416813d641d51 (this mistake was introduced when I created this example workspace by my fault)
And by adding `signature@1` into image nodes: https://github.com/dev-0x7C6/fit-signing-tests/commit/448e4200f884833bbbbb254178bc4e2889eee86e

I was using Yocto classes to sing and prepare `*.its` files. So I take them as strong reference in my work. Sadly `its` files generated by Yocto are not correct and missing `signature@1` nodes (they only contains singatures for configuration, which is insufficient). I was searching blindly for mistake everywhere else. I was even checking if data in fdt is correctly stored (e.g. endian encoding).

I can confirm that `ubpubkey.py` is working as expected and generating proper output.

**Comment by rkraevskiy** [comment]
I've fixed minor issues and added samples. Please checkout https://github.com/rkraevskiy/ubootpubkey/tree/master/tests/fit

**Comment by dev-0x7C6** [comment]
Ok, I probably now get it. `required = "conf";` changed behavior and signature nodes (in images sections) are no longer required. So with `required = "conf";` set in `u-boot.dtb` I can now progress with default Yocto `its` output.

Thanks for research :+1:
